import Nav from "@/components/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Stalone BJJ Chorley",
    template: "%s | Stalone BJJ Chorley",
  },
  description: "Brazilian Jiu-Jitsu in Chorley, Lancashire",
  keywords: [
    "Bjj near me",
    "Brazilian Jiu-Jitsu near me",
    "Martial Arts near me",
    "Mma near me",
    "Mixed Martial Arts near me",
    "Self Defence near me",
    "Self-Defence near me",
    "Self Defense near me",
    "Self-Defense near me",
    "ufc near me",
    "Fitness near me",
    "Health near me",
    "Bjj Chorley",
    "Brazilian Jiu-Jitsu Chorley",
    "Martial Arts Chorley",
    "Mma Chorley",
    "Mixed Martial Arts Chorley",
    "Self Defence Chorley",
    "Self-Defence Chorley",
    "Self Defense Chorley",
    "Self-Defense Chorley",
    "Fitness Chorley",
    "Health Chorley",
    "Bjj Lancashire",
    "Brazilian Jiu-Jitsu Lancashire",
    "Martial Arts Lancashire",
    "Mma Lancashire",
    "Mixed Martial Arts Lancashire",
    "Self Defence Lancashire",
    "Self-Defence Lancashire",
    "Self Defense Lancashire",
    "Self-Defense Lancashire",
    "Fitness Lancashire",
    "Health Lancashire",
    "Bjj Preston",
    "Brazilian Jiu-Jitsu Preston",
    "Martial Arts Preston",
    "Mma Preston",
    "Mixed Martial Arts Preston",
    "Self Defence Preston",
    "Self-Defence Preston",
    "Self Defense Preston",
    "Self-Defense Preston",
    "Fitness Preston",
    "Health Preston",
    "Bjj Bolton",
    "Brazilian Jiu-Jitsu Bolton",
    "Martial Arts Bolton",
    "Mma Bolton",
    "Mixed Martial Arts Bolton",
    "Self Defence Bolton",
    "Self-Defence Bolton",
    "Self Defense Bolton",
    "Self-Defense Bolton",
    "Fitness Bolton",
    "Health Bolton",
    "Bjj Wigan",
    "Brazilian Jiu-Jitsu Wigan",
    "Martial Arts Wigan",
    "Mma Wigan",
    "Mixed Martial Arts Wigan",
    "Self Defence Wigan",
    "Self-Defence Wigan",
    "Self Defense Wigan",
    "Self-Defense Wigan",
    "Fitness Wigan",
    "Health Wigan",
    "Bjj Horwich",
    "Brazilian Jiu-Jitsu Horwich",
    "Martial Arts Horwich",
    "Mma Horwich",
    "Mixed Martial Arts Horwich",
    "Self Defence Horwich",
    "Self-Defence Horwich",
    "Self Defense Horwich",
    "Self-Defense Horwich",
    "Fitness Horwich",
    "Health Horwich",
    "Brazilian Jiu-Jitsu",
    "Chorley",
    "Lancashire",
    "BJJ",
    "Stalone",
    "Stalone BJJ",
    "Stalone BJJ Chorley",
    "Stalone BJJ Lancashire",
    "Stalone Brazilian Jiu-Jitsu",
    "Stalone Brazilian Jiu-Jitsu Chorley",
    "Stalone Brazilian Jiu-Jitsu Lancashire",
    "Stalone Martial Arts",
    "Stalone Martial Arts Chorley",
    "Stalone Martial Arts Lancashire",
    "Stalone MMA",
    "Stalone MMA Chorley",
    "Stalone MMA Lancashire",
    "Stalone Mixed Martial Arts",
    "Stalone Mixed Martial Arts Chorley",
    "Stalone Mixed Martial Arts Lancashire",
    "Stalone",
    "Stallone",
    "Stallone BJJ",
    "Stallone BJJ Chorley",
    "Stallone BJJ Lancashire",
    "Stallone Brazilian Jiu-Jitsu",
    "Stallone Brazilian Jiu-Jitsu Chorley",
    "Stallone Brazilian Jiu-Jitsu Lancashire",
    "Stallone Martial Arts",
    "Stallone Martial Arts Chorley",
    "Stallone Martial Arts Lancashire",
    "Stallone MMA",
    "Martial Arts",
    "MMA",
    "Mixed Martial Arts",
    "Self Defence",
    "Self-Defence",
    "Self Defense",
    "Self-Defense",
    "Fitness",
    "Health",
    "Chorley BJJ",
    "Chorley Brazilian Jiu-Jitsu",
    "Chorley Martial Arts",
    "Chorley MMA",
    "Chorley Mixed Martial Arts",
    "Chorley Self Defence",
    "Chorley Self-Defence",
    "Chorley Self Defense",
    "Chorley Self-Defense",
    "Chorley Fitness",
    "Chorley Health",
    "Lancashire BJJ",
    "Lancashire Brazilian Jiu-Jitsu",
    "Lancashire Martial Arts",
    "Lancashire MMA",
    "Lancashire Mixed Martial Arts",
    "Lancashire Self Defence",
    "Lancashire Self-Defence",
    "Lancashire Self Defense",
    "Lancashire Self-Defense",
    "Lancashire Fitness",
    "Lancashire Health",
    "Preston BJJ",
    "Preston Brazilian Jiu-Jitsu",
    "Preston Martial Arts",
    "Preston MMA",
    "Preston Mixed Martial Arts",
    "Preston Self Defence",
    "Preston Self-Defence",
    "Preston Self Defense",
    "Preston Self-Defense",
    "Preston Fitness",
    "Preston Health",
    "Bolton BJJ",
    "Bolton Brazilian Jiu-Jitsu",
    "Bolton Martial Arts",
    "Bolton MMA",
    "Bolton Mixed Martial Arts",
    "Bolton Self Defence",
    "Bolton Self-Defence",
    "Bolton Self Defense",
    "Bolton Self-Defense",
    "Bolton Fitness",
    "Bolton Health",
    "Wigan BJJ",
    "Wigan Brazilian Jiu-Jitsu",
    "Wigan Martial Arts",
    "Wigan MMA",
    "Wigan Mixed Martial Arts",
    "Wigan Self Defence",
    "Wigan Self-Defence",
    "Wigan Self Defense",
    "Wigan Self-Defense",
    "Wigan Fitness",
    "Wigan Health",
    "Horwich BJJ",
    "Horwich Brazilian Jiu-Jitsu",
    "Horwich Martial Arts",
    "Horwich MMA",
    "Horwich Mixed Martial Arts",
    "Horwich Self Defence",
    "Horwich Self-Defence",
    "Horwich Self Defense",
    "Horwich Self-Defense",
    "Horwich Fitness",
    "Horwich Health",
    "Jiu-Jitsu",
    "Jiu Jitsu",
  ],
  alternates: {
    canonical: "https://stalonebjj.co.uk",
  },
  robots: {
    index: true,
    follow: true,
  },
  // verification: {
  //   google: ""
  // } IMPLEMENT THIS ASAP google verification for SEO purposes
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Nav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
